/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PcosRouteImport } from './routes/pcos'
import { Route as YogaFlowRouteImport } from './routes/yoga-flow'
import { Route as WelcomeSupplementsRouteImport } from './routes/welcome-supplements'
import { Route as WelcomeModeRouteImport } from './routes/welcome-mode'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as MedRouteImport } from './routes/med'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ConceiveRouteImport } from './routes/conceive'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as PregnantRouteImport } from './routes/pregnant'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WelcomeGoalsRouteImport } from './routes/welcome-goals'
import { Route as WelcomeLastPeriodRouteImport } from './routes/welcome-last-period'
import { Route as IndexRouteImport } from './routes/index'

const PcosRoute = PcosRouteImport.update({
  id: '/pcos',
  path: '/pcos',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaFlowRoute = YogaFlowRouteImport.update({
  id: '/yoga-flow',
  path: '/yoga-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeSupplementsRoute = WelcomeSupplementsRouteImport.update({
  id: '/welcome-supplements',
  path: '/welcome-supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeModeRoute = WelcomeModeRouteImport.update({
  id: '/welcome-mode',
  path: '/welcome-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const MedRoute = MedRouteImport.update({
  id: '/med',
  path: '/med',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceiveRoute = ConceiveRouteImport.update({
  id: '/conceive',
  path: '/conceive',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnantRoute = PregnantRouteImport.update({
  id: '/pregnant',
  path: '/pregnant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeGoalsRoute = WelcomeGoalsRouteImport.update({
  id: '/welcome-goals',
  path: '/welcome-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeLastPeriodRoute = WelcomeLastPeriodRouteImport.update({
  id: '/welcome-last-period',
  path: '/welcome-last-period',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/conceive': typeof ConceiveRoute
  '/content': typeof ContentRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRoute
  '/med': typeof MedRoute
  '/pcos': typeof PcosRoute
  '/pregnant': typeof PregnantRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
  '/welcome-goals': typeof WelcomeGoalsRoute
  '/welcome-last-period': typeof WelcomeLastPeriodRoute
  '/welcome-mode': typeof WelcomeModeRoute
  '/welcome-supplements': typeof WelcomeSupplementsRoute
  '/yoga-flow': typeof YogaFlowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/conceive': typeof ConceiveRoute
  '/content': typeof ContentRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRoute
  '/med': typeof MedRoute
  '/pcos': typeof PcosRoute
  '/pregnant': typeof PregnantRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
  '/welcome-goals': typeof WelcomeGoalsRoute
  '/welcome-last-period': typeof WelcomeLastPeriodRoute
  '/welcome-mode': typeof WelcomeModeRoute
  '/welcome-supplements': typeof WelcomeSupplementsRoute
  '/yoga-flow': typeof YogaFlowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/conceive': typeof ConceiveRoute
  '/content': typeof ContentRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRoute
  '/med': typeof MedRoute
  '/pcos': typeof PcosRoute
  '/pregnant': typeof PregnantRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
  '/welcome-goals': typeof WelcomeGoalsRoute
  '/welcome-last-period': typeof WelcomeLastPeriodRoute
  '/welcome-mode': typeof WelcomeModeRoute
  '/welcome-supplements': typeof WelcomeSupplementsRoute
  '/yoga-flow': typeof YogaFlowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/calendar'
    | '/coach'
    | '/conceive'
    | '/content'
    | '/health'
    | '/learn'
    | '/med'
    | '/pcos'
    | '/pregnant'
    | '/profile'
    | '/shop'
    | '/track'
    | '/welcome'
    | '/welcome-goals'
    | '/welcome-last-period'
    | '/welcome-mode'
    | '/welcome-supplements'
    | '/yoga-flow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/calendar'
    | '/coach'
    | '/conceive'
    | '/content'
    | '/health'
    | '/learn'
    | '/med'
    | '/pcos'
    | '/pregnant'
    | '/profile'
    | '/shop'
    | '/track'
    | '/welcome'
    | '/welcome-goals'
    | '/welcome-last-period'
    | '/welcome-mode'
    | '/welcome-supplements'
    | '/yoga-flow'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/calendar'
    | '/coach'
    | '/conceive'
    | '/content'
    | '/health'
    | '/learn'
    | '/med'
    | '/pcos'
    | '/pregnant'
    | '/profile'
    | '/shop'
    | '/track'
    | '/welcome'
    | '/welcome-goals'
    | '/welcome-last-period'
    | '/welcome-mode'
    | '/welcome-supplements'
    | '/yoga-flow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRoute
  ConceiveRoute: typeof ConceiveRoute
  ContentRoute: typeof ContentRoute
  HealthRoute: typeof HealthRoute
  LearnRoute: typeof LearnRoute
  MedRoute: typeof MedRoute
  PcosRoute: typeof PcosRoute
  PregnantRoute: typeof PregnantRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  TrackRoute: typeof TrackRoute
  WelcomeRoute: typeof WelcomeRoute
  WelcomeGoalsRoute: typeof WelcomeGoalsRoute
  WelcomeLastPeriodRoute: typeof WelcomeLastPeriodRoute
  WelcomeModeRoute: typeof WelcomeModeRoute
  WelcomeSupplementsRoute: typeof WelcomeSupplementsRoute
  YogaFlowRoute: typeof YogaFlowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pcos': {
      id: '/pcos'
      path: '/pcos'
      fullPath: '/pcos'
      preLoaderRoute: typeof PcosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-flow': {
      id: '/yoga-flow'
      path: '/yoga-flow'
      fullPath: '/yoga-flow'
      preLoaderRoute: typeof YogaFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome-supplements': {
      id: '/welcome-supplements'
      path: '/welcome-supplements'
      fullPath: '/welcome-supplements'
      preLoaderRoute: typeof WelcomeSupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome-mode': {
      id: '/welcome-mode'
      path: '/welcome-mode'
      fullPath: '/welcome-mode'
      preLoaderRoute: typeof WelcomeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/med': {
      id: '/med'
      path: '/med'
      fullPath: '/med'
      preLoaderRoute: typeof MedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conceive': {
      id: '/conceive'
      path: '/conceive'
      fullPath: '/conceive'
      preLoaderRoute: typeof ConceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnant': {
      id: '/pregnant'
      path: '/pregnant'
      fullPath: '/pregnant'
      preLoaderRoute: typeof PregnantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome-goals': {
      id: '/welcome-goals'
      path: '/welcome-goals'
      fullPath: '/welcome-goals'
      preLoaderRoute: typeof WelcomeGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome-last-period': {
      id: '/welcome-last-period'
      path: '/welcome-last-period'
      fullPath: '/welcome-last-period'
      preLoaderRoute: typeof WelcomeLastPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRoute,
  ConceiveRoute: ConceiveRoute,
  ContentRoute: ContentRoute,
  HealthRoute: HealthRoute,
  LearnRoute: LearnRoute,
  MedRoute: MedRoute,
  PcosRoute: PcosRoute,
  PregnantRoute: PregnantRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  TrackRoute: TrackRoute,
  WelcomeRoute: WelcomeRoute,
  WelcomeGoalsRoute: WelcomeGoalsRoute,
  WelcomeLastPeriodRoute: WelcomeLastPeriodRoute,
  WelcomeModeRoute: WelcomeModeRoute,
  WelcomeSupplementsRoute: WelcomeSupplementsRoute,
  YogaFlowRoute: YogaFlowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
