/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeSupplementsRouteImport } from './routes/welcome-supplements'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrackRouteImport } from './routes/track'
import { Route as MedRouteImport } from './routes/med'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeSupplementsRoute = WelcomeSupplementsRouteImport.update({
  id: '/welcome-supplements',
  path: '/welcome-supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const MedRoute = MedRouteImport.update({
  id: '/med',
  path: '/med',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/calendar': typeof CalendarRoute
  '/content': typeof ContentRoute
  '/med': typeof MedRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
  '/welcome-supplements': typeof WelcomeSupplementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/calendar': typeof CalendarRoute
  '/content': typeof ContentRoute
  '/med': typeof MedRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
  '/welcome-supplements': typeof WelcomeSupplementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/calendar': typeof CalendarRoute
  '/content': typeof ContentRoute
  '/med': typeof MedRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
  '/welcome-supplements': typeof WelcomeSupplementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/calendar'
    | '/content'
    | '/med'
    | '/track'
    | '/welcome'
    | '/welcome-supplements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/calendar'
    | '/content'
    | '/med'
    | '/track'
    | '/welcome'
    | '/welcome-supplements'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/calendar'
    | '/content'
    | '/med'
    | '/track'
    | '/welcome'
    | '/welcome-supplements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CalendarRoute: typeof CalendarRoute
  ContentRoute: typeof ContentRoute
  MedRoute: typeof MedRoute
  TrackRoute: typeof TrackRoute
  WelcomeRoute: typeof WelcomeRoute
  WelcomeSupplementsRoute: typeof WelcomeSupplementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-supplements': {
      id: '/welcome-supplements'
      path: '/welcome-supplements'
      fullPath: '/welcome-supplements'
      preLoaderRoute: typeof WelcomeSupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/med': {
      id: '/med'
      path: '/med'
      fullPath: '/med'
      preLoaderRoute: typeof MedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CalendarRoute: CalendarRoute,
  ContentRoute: ContentRoute,
  MedRoute: MedRoute,
  TrackRoute: TrackRoute,
  WelcomeRoute: WelcomeRoute,
  WelcomeSupplementsRoute: WelcomeSupplementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
